name: Build iOS IPA

on: [workflow_dispatch]

jobs:
  ios-build:
    runs-on: macos-15
    timeout-minutes: 30

    env:
      BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
      BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      KEYCHAIN_NAME: build.keychain
      PROFILE_NAME: RouticoDEV
      BUNDLE_ID: com.karamsawalha.routico
      APP_STORE_TEAM_ID: ${{ secrets.APP_STORE_TEAM_ID }}
      versionName: ${{ secrets.versionName }}
      versionNumber: ${{ secrets.versionNumber }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'
          channel: stable
          cache: true

      - name: Setup Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Fastlane
        run: gem install fastlane

      - name: Clean and fetch Flutter dependencies
        run: |
          flutter clean
          flutter pub get
          flutter pub run flutter_launcher_icons:main

      - name: Import certificate into keychain
        run: |
          echo "$BUILD_CERTIFICATE_BASE64" | base64 --decode > "$RUNNER_TEMP/cert.p12"
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_NAME"
          security import "$RUNNER_TEMP/cert.p12" -k "$KEYCHAIN_NAME" -P "$P12_PASSWORD" -T /usr/bin/codesign -A
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
          security list-keychains -s "$KEYCHAIN_NAME" $(security list-keychains -d user | tr -d '"')

      - name: Decode and install provisioning profile
        run: |
          echo "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode > RouticoDEV.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp RouticoDEV.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Install CocoaPods
        run: |
          pushd ios
          pod install --repo-update
          popd

      - name: Generate iOS build files (no codesign)
        run: flutter build ios --release --no-codesign --build-name="${versionName}" --build-number=$(expr $versionNumber + 1)

      - name: Archive and export IPA with Development signing
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            archive \
            DEVELOPMENT_TEAM="$APP_STORE_TEAM_ID" \
            CODE_SIGN_IDENTITY="Apple Development" \
            CODE_SIGN_STYLE="Manual" \
            -allowProvisioningUpdates

          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/export \
            -allowProvisioningUpdates

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: routico-ipa
          path: build/export/*.ipa

      - name: Cleanup keychain
        run: security delete-keychain "$KEYCHAIN_NAME"
